GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJKb2huIiwiZW1haWwiOiI0VmQ3dkBleGFtcGxlLmNvbSIsInBhc3N3b3JkIjoiMTIzIiwiaWF0IjoxNzIzNTE2MzI0fQ.c_5rDUskmturchcHbeyE7eEBgJbCn1uP6tb7Ksj_IwM

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "4Vd7v@example.com",
    "password": "123"
}   